/query?DB1Col=School+Sex+GradYear&DB2Col=Quart+Ann_Income&&&&Iv1Col=DB1.Sex&Agg1Func=Min&Agg1Col=DB2.Ann_Income&Agg2Func=Avg&Agg2Col=DB2.Ann_Income&Agg3Func=Max&Agg3Col=DB2.Ann_Income&Agg4Func=Stdev&Agg4Col=DB2.Ann_Income
